/**
 * @fileoverview Closed lookup tables `normalizeUpstreamText` reads: the Highwire
 * symbol placeholders bioRxiv/medRxiv exports leave in titles and abstracts
 * (`{beta}`, `[&ge;]`, …) with the character each stands for, and the section
 * headings structured abstracts fuse onto their first sentence
 * (`ResultsInsulin-secreting …`). Derived from 5,788 live `/details` records
 * across 14 bioRxiv and medRxiv windows (2021-03 to 2026-09), with glyphs
 * checked against EuropePMC's rendering of the same records. Both tables are
 * closed on purpose: a name or heading missing here passes through verbatim,
 * so a misread can only leave text as upstream sent it, never rewrite it.
 * @module services/upstream-text-tables
 */

/**
 * The Greek letters, by the LaTeX names Highwire uses. Shared by the brace and
 * bracket forms (`{beta}`, `TGF[beta]`). `epsilon`/`phi` follow LaTeX
 * (`ϵ`/`ϕ`) and `varepsilon`/`varphi` its variants (`ε`/`φ`), matching
 * EuropePMC's rendering of the same records.
 */
const GREEK: Readonly<Record<string, string>> = {
  alpha: 'α',
  beta: 'β',
  gamma: 'γ',
  delta: 'δ',
  epsilon: 'ϵ',
  varepsilon: 'ε',
  zeta: 'ζ',
  eta: 'η',
  theta: 'θ',
  vartheta: 'ϑ',
  iota: 'ι',
  kappa: 'κ',
  lambda: 'λ',
  mu: 'μ',
  nu: 'ν',
  xi: 'ξ',
  pi: 'π',
  rho: 'ρ',
  sigma: 'σ',
  varsigma: 'ς',
  tau: 'τ',
  upsilon: 'υ',
  phi: 'ϕ',
  varphi: 'φ',
  chi: 'χ',
  psi: 'ψ',
  omega: 'ω',
  Gamma: 'Γ',
  Delta: 'Δ',
  Theta: 'Θ',
  Lambda: 'Λ',
  Xi: 'Ξ',
  Pi: 'Π',
  Sigma: 'Σ',
  Upsilon: 'Υ',
  Phi: 'Φ',
  Psi: 'Ψ',
  Omega: 'Ω',
};

/**
 * `{name}` placeholders. `o` is the ordinal-style degree sign upstream writes
 * as `19 {o}C`; `triangleup` marks a deletion mutant (`{triangleup}pp2a`), which
 * EuropePMC renders as `Δ`. `square` is a glyph the export itself lost, kept as
 * `□` (EuropePMC shows the same) because dropping it would corrupt a unit:
 * `ha{square}{superscript 1}` is ha⁻¹.
 */
export const BRACE_PLACEHOLDERS: Readonly<Record<string, string>> = {
  ...GREEK,
  '+/-': '±',
  approx: '≈',
  cap: '∩',
  degrees: '°',
  downarrow: '↓',
  euro: '€',
  gtrsim: '≳',
  infty: '∞',
  'inverted exclamation': '¡',
  micro: 'µ',
  'middle dot': '·',
  o: 'º',
  paragraph: '¶',
  pound: '£',
  Rightarrow: '⇒',
  square: '□',
  'superscript 0': '⁰',
  'superscript 1': '¹',
  'superscript 2': '²',
  'superscript 3': '³',
  'superscript 4': '⁴',
  'superscript 5': '⁵',
  'superscript 6': '⁶',
  'superscript 7': '⁷',
  'superscript 8': '⁸',
  'superscript 9': '⁹',
  triangleup: 'Δ',
  uparrow: '↑',
  whitebullet: '◦',
};

/**
 * `[name]` placeholders. The HTML-entity forms are the only place `&ge;`,
 * `&le;`, and `&gt;` occur upstream: `[-&gt;]` is an arrow, not `[->]`.
 * `[xHHHH]` code points are read separately. Single letters are deliberately
 * absent — `[A]` is Å and `[a]` is α in some records, but `[A]`, `[E]`, and
 * `[R]` are also concentration and set notation, so they stay verbatim.
 */
export const BRACKET_PLACEHOLDERS: Readonly<Record<string, string>> = {
  ...GREEK,
  '~': '∼',
  '~=': '≃',
  '-': '―',
  '&ge;': '≥',
  '&le;': '≤',
  '-&gt;': '→',
  bullet: '•',
  isin: '∈',
  tpltrtarr: '➢',
};

/**
 * Section headings structured abstracts open a paragraph with, lowercase.
 * Matched case-insensitively against the start of a paragraph and only when
 * the body follows with no separator (or the heading stands alone on its
 * line), so a paragraph that opens with a CamelCase name — `AlphaFold`,
 * `ChatGPT`, `DesignMaster` — is never split: none of those prefixes is here.
 */
export const SECTION_HEADINGS: readonly string[] = [
  'abstract',
  'abstract summary',
  'added value of this study',
  'advances in knowledge',
  'aim',
  'aim and objectives',
  'aims',
  'aims/objectives',
  'approach',
  'approach and results',
  'approaches & results',
  'article summary',
  'author summary',
  'authors summary',
  'availability',
  'availability and implementation',
  'background',
  'background & aims',
  'background and aim',
  'background and aims',
  'background and hypothesis',
  'background and objective',
  'background and objectives',
  'background and purpose',
  'background/aim',
  'background/aims',
  'background/objectives',
  'brief summary',
  'case presentation',
  'clinical trial registration',
  'code availability',
  'competing interests',
  'conclusion',
  'conclusion and implications',
  'conclusion and recommendation',
  'conclusion and relevance',
  'conclusion and significance',
  'conclusions',
  'conclusions & significance',
  'conclusions and clinical implications',
  'conclusions and implications',
  'conclusions and relevance',
  'conclusions/significance',
  'condensed abstract',
  'data availability',
  'data availability statement',
  'data extraction',
  'data extraction and synthesis',
  'data sources',
  'data summary',
  'data synthesis',
  'declaration of interests',
  'design',
  'design and setting',
  'design, setting and participants',
  'design, setting, and participants',
  'design, setting, participants',
  'discussion',
  'discussion and conclusion',
  'discussion and conclusions',
  'eligible participants',
  'ethics and dissemination',
  'evidence before this study',
  'experimental approach',
  'experimental design',
  'exposure',
  'exposures',
  'findings',
  'funding',
  'highlight',
  'highlights',
  'how this study might affect research, practice or policy',
  'how this study might affect research, practice, or policy',
  'hypothesis',
  'impact statement',
  'implications of all available evidence',
  'implications of all the available evidence',
  'implications of the available evidence',
  'importance',
  'importance of the study',
  'in brief',
  'interpretation',
  'intervention',
  'interventions',
  'introduction',
  'introduction and objectives',
  'key findings',
  'key message',
  'key messages',
  'key points',
  'key results',
  'lay summary',
  'limitations',
  'location',
  'main conclusion',
  'main conclusions',
  'main outcome measure',
  'main outcome measures',
  'main outcome(s) and measure(s)',
  'main outcomes and measures',
  'main results',
  'material and methods',
  'materials and methods',
  'meaning',
  'meanings',
  'measurements and main results',
  'method',
  'methodology',
  'methodology/principal findings',
  'methods',
  'methods & materials',
  'methods & results',
  'methods and analysis',
  'methods and findings',
  'methods and materials',
  'methods and procedures',
  'methods and results',
  'motivation',
  'new and noteworthy',
  'objective',
  'objective(s)',
  'objectives',
  'one sentence summary',
  'one-sentence summary',
  'outcome measures',
  'outcomes',
  'participants',
  'patients',
  'patients and methods',
  'plain english summary',
  'plain language summary',
  'primary and secondary outcome measures',
  'principal findings',
  'purpose',
  'rationale',
  'registration',
  'research in context',
  'research question',
  'result',
  'results',
  'results and conclusion',
  'results and conclusions',
  'setting',
  'significance',
  'significance statement',
  'simple summary',
  'statement of significance',
  'study design',
  'study selection',
  'summary',
  'summary statement',
  'synopsis',
  'teaser',
  'the implications',
  'the known',
  'the new',
  'translational relevance',
  'translational significance',
  'trial registration',
  'what is already known on this subject',
  'what is already known on this topic',
  'what is known already',
  'what this study adds',
];

/**
 * Headings that also open gene symbols — `AIM1`, `AIM2`, and mouse `Aim2` — so
 * they are never split before a digit (`AIM2 is a cytosolic DNA sensor` stays
 * whole). No sampled record fuses either heading to a digit-led body; both do
 * fuse to words and acronyms (`AimTo`, `AimsSCORE2`), which still split.
 */
export const GENE_SYMBOL_HEADINGS: ReadonlySet<string> = new Set(['aim', 'aims']);
